import{S as p,i as l}from"./assets/vendor-5b791d57.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const h="42472601-e2efb745d6431960b7108569a",y=document.getElementById("search-form"),g=document.getElementById("search-input"),a=document.getElementById("loader"),c=document.getElementById("gallery"),E=new p(".gallery a");y.addEventListener("submit",function(n){n.preventDefault();const o=g.value.trim();if(o===""){l.error({title:"Error",message:"Please enter a search term!"});return}a.style.display="block",c.innerHTML="",L(o).then(t=>{setTimeout(()=>{a.style.display="none"},500),t.hits.length===0?l.warning({title:"No results",message:"Sorry, there are no images matching your search.Please try again!"}):b(t.hits)}).catch(t=>{a.style.display="none",l.error({title:"Error",message:"An error occurred while fetching images. Please try again!"}),console.error("Error fetching images:",t)})});function L(n){const o=`https://pixabay.com/api/?key=${h}&q=${n}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(o).then(t=>{if(!t.ok)throw new Error(`HTTP error! Status: ${t.status}`);return t.json()})}function b(n){const o=n.map(({webformatURL:e,largeImageURL:r,tags:s,likes:d,views:u,comments:m,downloads:f})=>`<div class="card">
      <a href="${r}" data-lightbox="gallery" data-title="${s}">
        <img src="${e}" alt="${s}" title="${s}"/>
      </a>
      <div class="card-border">
      <p>Likes: ${d}</p>
      <p>Views: ${u}</p>
      <p>Comments: ${m}</p>
      <p>Downloads: ${f}</p>
      </div>
    </div>`);c.innerHTML=o.join("");const t=c.querySelectorAll("img"),i=Array.from(t).map(e=>new Promise((r,s)=>{e.onload=r,e.onerror=s}));Promise.all(i).then(()=>{a.style.display="none"}).catch(e=>{console.error("Error loading images:",e)}),E.refresh()}
//# sourceMappingURL=commonHelpers.js.map
